//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace China.ICBC.DAL.ORM.ICBC
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    internal partial class ICBC_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ICBC_Entities object using the connection string found in the 'ICBC_Entities' section of the application configuration file.
        /// </summary>
        public ICBC_Entities() : base("name=ICBC_Entities", "ICBC_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ICBC_Entities object.
        /// </summary>
        public ICBC_Entities(string connectionString) : base(connectionString, "ICBC_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ICBC_Entities object.
        /// </summary>
        public ICBC_Entities(EntityConnection connection) : base(connection, "ICBC_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<China_ICBC_Hieroglyphs> China_ICBC_Hieroglyphs
        {
            get
            {
                if ((_China_ICBC_Hieroglyphs == null))
                {
                    _China_ICBC_Hieroglyphs = base.CreateObjectSet<China_ICBC_Hieroglyphs>("China_ICBC_Hieroglyphs");
                }
                return _China_ICBC_Hieroglyphs;
            }
        }
        private ObjectSet<China_ICBC_Hieroglyphs> _China_ICBC_Hieroglyphs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<China_ICBC_Transactions> China_ICBC_Transactions
        {
            get
            {
                if ((_China_ICBC_Transactions == null))
                {
                    _China_ICBC_Transactions = base.CreateObjectSet<China_ICBC_Transactions>("China_ICBC_Transactions");
                }
                return _China_ICBC_Transactions;
            }
        }
        private ObjectSet<China_ICBC_Transactions> _China_ICBC_Transactions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<China_ICBC_ProvincialBranch> China_ICBC_ProvincialBranch
        {
            get
            {
                if ((_China_ICBC_ProvincialBranch == null))
                {
                    _China_ICBC_ProvincialBranch = base.CreateObjectSet<China_ICBC_ProvincialBranch>("China_ICBC_ProvincialBranch");
                }
                return _China_ICBC_ProvincialBranch;
            }
        }
        private ObjectSet<China_ICBC_ProvincialBranch> _China_ICBC_ProvincialBranch;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the China_ICBC_Hieroglyphs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChina_ICBC_Hieroglyphs(China_ICBC_Hieroglyphs china_ICBC_Hieroglyphs)
        {
            base.AddObject("China_ICBC_Hieroglyphs", china_ICBC_Hieroglyphs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the China_ICBC_Transactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChina_ICBC_Transactions(China_ICBC_Transactions china_ICBC_Transactions)
        {
            base.AddObject("China_ICBC_Transactions", china_ICBC_Transactions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the China_ICBC_ProvincialBranch EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChina_ICBC_ProvincialBranch(China_ICBC_ProvincialBranch china_ICBC_ProvincialBranch)
        {
            base.AddObject("China_ICBC_ProvincialBranch", china_ICBC_ProvincialBranch);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="paymentSystem">No Metadata Documentation available.</param>
        /// <param name="dateTime">No Metadata Documentation available.</param>
        /// <param name="messageType">No Metadata Documentation available.</param>
        /// <param name="messageSwift">No Metadata Documentation available.</param>
        /// <param name="messageObject">No Metadata Documentation available.</param>
        public ObjectResult<spChina_ICBC_Transactions_Insert_Result> spChina_ICBC_Transactions_Insert(global::System.String paymentSystem, Nullable<global::System.DateTime> dateTime, global::System.String messageType, global::System.String messageSwift, global::System.Byte[] messageObject)
        {
            ObjectParameter paymentSystemParameter;
            if (paymentSystem != null)
            {
                paymentSystemParameter = new ObjectParameter("PaymentSystem", paymentSystem);
            }
            else
            {
                paymentSystemParameter = new ObjectParameter("PaymentSystem", typeof(global::System.String));
            }
    
            ObjectParameter dateTimeParameter;
            if (dateTime.HasValue)
            {
                dateTimeParameter = new ObjectParameter("DateTime", dateTime);
            }
            else
            {
                dateTimeParameter = new ObjectParameter("DateTime", typeof(global::System.DateTime));
            }
    
            ObjectParameter messageTypeParameter;
            if (messageType != null)
            {
                messageTypeParameter = new ObjectParameter("MessageType", messageType);
            }
            else
            {
                messageTypeParameter = new ObjectParameter("MessageType", typeof(global::System.String));
            }
    
            ObjectParameter messageSwiftParameter;
            if (messageSwift != null)
            {
                messageSwiftParameter = new ObjectParameter("MessageSwift", messageSwift);
            }
            else
            {
                messageSwiftParameter = new ObjectParameter("MessageSwift", typeof(global::System.String));
            }
    
            ObjectParameter messageObjectParameter;
            if (messageObject != null)
            {
                messageObjectParameter = new ObjectParameter("MessageObject", messageObject);
            }
            else
            {
                messageObjectParameter = new ObjectParameter("MessageObject", typeof(global::System.Byte[]));
            }
    
            return base.ExecuteFunction<spChina_ICBC_Transactions_Insert_Result>("spChina_ICBC_Transactions_Insert", paymentSystemParameter, dateTimeParameter, messageTypeParameter, messageSwiftParameter, messageObjectParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICBC", Name="China_ICBC_Hieroglyphs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class China_ICBC_Hieroglyphs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new China_ICBC_Hieroglyphs object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="hieroglyph">Initial value of the Hieroglyph property.</param>
        /// <param name="hieroglyphCode">Initial value of the HieroglyphCode property.</param>
        /// <param name="rowID">Initial value of the RowID property.</param>
        public static China_ICBC_Hieroglyphs CreateChina_ICBC_Hieroglyphs(global::System.String name, global::System.String hieroglyph, global::System.String hieroglyphCode, global::System.Int32 rowID)
        {
            China_ICBC_Hieroglyphs china_ICBC_Hieroglyphs = new China_ICBC_Hieroglyphs();
            china_ICBC_Hieroglyphs.Name = name;
            china_ICBC_Hieroglyphs.Hieroglyph = hieroglyph;
            china_ICBC_Hieroglyphs.HieroglyphCode = hieroglyphCode;
            china_ICBC_Hieroglyphs.RowID = rowID;
            return china_ICBC_Hieroglyphs;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Hieroglyph
        {
            get
            {
                return _Hieroglyph;
            }
            set
            {
                OnHieroglyphChanging(value);
                ReportPropertyChanging("Hieroglyph");
                _Hieroglyph = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Hieroglyph");
                OnHieroglyphChanged();
            }
        }
        private global::System.String _Hieroglyph;
        partial void OnHieroglyphChanging(global::System.String value);
        partial void OnHieroglyphChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HieroglyphCode
        {
            get
            {
                return _HieroglyphCode;
            }
            set
            {
                OnHieroglyphCodeChanging(value);
                ReportPropertyChanging("HieroglyphCode");
                _HieroglyphCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HieroglyphCode");
                OnHieroglyphCodeChanged();
            }
        }
        private global::System.String _HieroglyphCode;
        partial void OnHieroglyphCodeChanging(global::System.String value);
        partial void OnHieroglyphCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RowID
        {
            get
            {
                return _RowID;
            }
            set
            {
                if (_RowID != value)
                {
                    OnRowIDChanging(value);
                    ReportPropertyChanging("RowID");
                    _RowID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RowID");
                    OnRowIDChanged();
                }
            }
        }
        private global::System.Int32 _RowID;
        partial void OnRowIDChanging(global::System.Int32 value);
        partial void OnRowIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICBC", Name="China_ICBC_ProvincialBranch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class China_ICBC_ProvincialBranch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new China_ICBC_ProvincialBranch object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="sWIFT">Initial value of the SWIFT property.</param>
        public static China_ICBC_ProvincialBranch CreateChina_ICBC_ProvincialBranch(global::System.String name, global::System.String address, global::System.String sWIFT)
        {
            China_ICBC_ProvincialBranch china_ICBC_ProvincialBranch = new China_ICBC_ProvincialBranch();
            china_ICBC_ProvincialBranch.Name = name;
            china_ICBC_ProvincialBranch.Address = address;
            china_ICBC_ProvincialBranch.SWIFT = sWIFT;
            return china_ICBC_ProvincialBranch;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SWIFT
        {
            get
            {
                return _SWIFT;
            }
            set
            {
                OnSWIFTChanging(value);
                ReportPropertyChanging("SWIFT");
                _SWIFT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SWIFT");
                OnSWIFTChanged();
            }
        }
        private global::System.String _SWIFT;
        partial void OnSWIFTChanging(global::System.String value);
        partial void OnSWIFTChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICBC", Name="China_ICBC_Transactions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class China_ICBC_Transactions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new China_ICBC_Transactions object.
        /// </summary>
        /// <param name="paymentSystem">Initial value of the PaymentSystem property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="orderNumber">Initial value of the OrderNumber property.</param>
        /// <param name="swiftTransactionNumber">Initial value of the SwiftTransactionNumber property.</param>
        /// <param name="messageType">Initial value of the MessageType property.</param>
        /// <param name="messageSwift">Initial value of the MessageSwift property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="messageObject">Initial value of the MessageObject property.</param>
        /// <param name="isFileSent">Initial value of the IsFileSent property.</param>
        public static China_ICBC_Transactions CreateChina_ICBC_Transactions(global::System.String paymentSystem, global::System.DateTime date, global::System.Int32 orderNumber, global::System.String swiftTransactionNumber, global::System.String messageType, global::System.String messageSwift, global::System.TimeSpan time, global::System.Byte[] messageObject, global::System.Boolean isFileSent)
        {
            China_ICBC_Transactions china_ICBC_Transactions = new China_ICBC_Transactions();
            china_ICBC_Transactions.PaymentSystem = paymentSystem;
            china_ICBC_Transactions.Date = date;
            china_ICBC_Transactions.OrderNumber = orderNumber;
            china_ICBC_Transactions.SwiftTransactionNumber = swiftTransactionNumber;
            china_ICBC_Transactions.MessageType = messageType;
            china_ICBC_Transactions.MessageSwift = messageSwift;
            china_ICBC_Transactions.Time = time;
            china_ICBC_Transactions.MessageObject = messageObject;
            china_ICBC_Transactions.IsFileSent = isFileSent;
            return china_ICBC_Transactions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PaymentSystem
        {
            get
            {
                return _PaymentSystem;
            }
            set
            {
                if (_PaymentSystem != value)
                {
                    OnPaymentSystemChanging(value);
                    ReportPropertyChanging("PaymentSystem");
                    _PaymentSystem = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PaymentSystem");
                    OnPaymentSystemChanged();
                }
            }
        }
        private global::System.String _PaymentSystem;
        partial void OnPaymentSystemChanging(global::System.String value);
        partial void OnPaymentSystemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderNumber
        {
            get
            {
                return _OrderNumber;
            }
            set
            {
                if (_OrderNumber != value)
                {
                    OnOrderNumberChanging(value);
                    ReportPropertyChanging("OrderNumber");
                    _OrderNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderNumber");
                    OnOrderNumberChanged();
                }
            }
        }
        private global::System.Int32 _OrderNumber;
        partial void OnOrderNumberChanging(global::System.Int32 value);
        partial void OnOrderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SwiftTransactionNumber
        {
            get
            {
                return _SwiftTransactionNumber;
            }
            set
            {
                OnSwiftTransactionNumberChanging(value);
                ReportPropertyChanging("SwiftTransactionNumber");
                _SwiftTransactionNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SwiftTransactionNumber");
                OnSwiftTransactionNumberChanged();
            }
        }
        private global::System.String _SwiftTransactionNumber;
        partial void OnSwiftTransactionNumberChanging(global::System.String value);
        partial void OnSwiftTransactionNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageType
        {
            get
            {
                return _MessageType;
            }
            set
            {
                OnMessageTypeChanging(value);
                ReportPropertyChanging("MessageType");
                _MessageType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageType");
                OnMessageTypeChanged();
            }
        }
        private global::System.String _MessageType;
        partial void OnMessageTypeChanging(global::System.String value);
        partial void OnMessageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageSwift
        {
            get
            {
                return _MessageSwift;
            }
            set
            {
                OnMessageSwiftChanging(value);
                ReportPropertyChanging("MessageSwift");
                _MessageSwift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageSwift");
                OnMessageSwiftChanged();
            }
        }
        private global::System.String _MessageSwift;
        partial void OnMessageSwiftChanging(global::System.String value);
        partial void OnMessageSwiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.TimeSpan _Time;
        partial void OnTimeChanging(global::System.TimeSpan value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Код_проверки_платежа
        {
            get
            {
                return _Код_проверки_платежа;
            }
            set
            {
                OnКод_проверки_платежаChanging(value);
                ReportPropertyChanging("Код_проверки_платежа");
                _Код_проверки_платежа = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Код_проверки_платежа");
                OnКод_проверки_платежаChanged();
            }
        }
        private Nullable<global::System.Int32> _Код_проверки_платежа;
        partial void OnКод_проверки_платежаChanging(Nullable<global::System.Int32> value);
        partial void OnКод_проверки_платежаChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Код_платежа
        {
            get
            {
                return _Код_платежа;
            }
            set
            {
                OnКод_платежаChanging(value);
                ReportPropertyChanging("Код_платежа");
                _Код_платежа = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Код_платежа");
                OnКод_платежаChanged();
            }
        }
        private Nullable<global::System.Int32> _Код_платежа;
        partial void OnКод_платежаChanging(Nullable<global::System.Int32> value);
        partial void OnКод_платежаChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] MessageObject
        {
            get
            {
                return StructuralObject.GetValidValue(_MessageObject);
            }
            set
            {
                OnMessageObjectChanging(value);
                ReportPropertyChanging("MessageObject");
                _MessageObject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageObject");
                OnMessageObjectChanged();
            }
        }
        private global::System.Byte[] _MessageObject;
        partial void OnMessageObjectChanging(global::System.Byte[] value);
        partial void OnMessageObjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFileSent
        {
            get
            {
                return _IsFileSent;
            }
            set
            {
                OnIsFileSentChanging(value);
                ReportPropertyChanging("IsFileSent");
                _IsFileSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFileSent");
                OnIsFileSentChanged();
            }
        }
        private global::System.Boolean _IsFileSent;
        partial void OnIsFileSentChanging(global::System.Boolean value);
        partial void OnIsFileSentChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ICBC", Name="spChina_ICBC_Transactions_Insert_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spChina_ICBC_Transactions_Insert_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spChina_ICBC_Transactions_Insert_Result object.
        /// </summary>
        /// <param name="paymentSystem">Initial value of the PaymentSystem property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="orderNumber">Initial value of the OrderNumber property.</param>
        /// <param name="swiftTransactionNumber">Initial value of the SwiftTransactionNumber property.</param>
        /// <param name="messageType">Initial value of the MessageType property.</param>
        /// <param name="messageSwift">Initial value of the MessageSwift property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="messageObject">Initial value of the MessageObject property.</param>
        public static spChina_ICBC_Transactions_Insert_Result CreatespChina_ICBC_Transactions_Insert_Result(global::System.String paymentSystem, global::System.DateTime date, global::System.Int32 orderNumber, global::System.String swiftTransactionNumber, global::System.String messageType, global::System.String messageSwift, global::System.TimeSpan time, global::System.Byte[] messageObject)
        {
            spChina_ICBC_Transactions_Insert_Result spChina_ICBC_Transactions_Insert_Result = new spChina_ICBC_Transactions_Insert_Result();
            spChina_ICBC_Transactions_Insert_Result.PaymentSystem = paymentSystem;
            spChina_ICBC_Transactions_Insert_Result.Date = date;
            spChina_ICBC_Transactions_Insert_Result.OrderNumber = orderNumber;
            spChina_ICBC_Transactions_Insert_Result.SwiftTransactionNumber = swiftTransactionNumber;
            spChina_ICBC_Transactions_Insert_Result.MessageType = messageType;
            spChina_ICBC_Transactions_Insert_Result.MessageSwift = messageSwift;
            spChina_ICBC_Transactions_Insert_Result.Time = time;
            spChina_ICBC_Transactions_Insert_Result.MessageObject = messageObject;
            return spChina_ICBC_Transactions_Insert_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PaymentSystem
        {
            get
            {
                return _PaymentSystem;
            }
            set
            {
                OnPaymentSystemChanging(value);
                ReportPropertyChanging("PaymentSystem");
                _PaymentSystem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PaymentSystem");
                OnPaymentSystemChanged();
            }
        }
        private global::System.String _PaymentSystem;
        partial void OnPaymentSystemChanging(global::System.String value);
        partial void OnPaymentSystemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderNumber
        {
            get
            {
                return _OrderNumber;
            }
            set
            {
                OnOrderNumberChanging(value);
                ReportPropertyChanging("OrderNumber");
                _OrderNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderNumber");
                OnOrderNumberChanged();
            }
        }
        private global::System.Int32 _OrderNumber;
        partial void OnOrderNumberChanging(global::System.Int32 value);
        partial void OnOrderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SwiftTransactionNumber
        {
            get
            {
                return _SwiftTransactionNumber;
            }
            set
            {
                OnSwiftTransactionNumberChanging(value);
                ReportPropertyChanging("SwiftTransactionNumber");
                _SwiftTransactionNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SwiftTransactionNumber");
                OnSwiftTransactionNumberChanged();
            }
        }
        private global::System.String _SwiftTransactionNumber;
        partial void OnSwiftTransactionNumberChanging(global::System.String value);
        partial void OnSwiftTransactionNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageType
        {
            get
            {
                return _MessageType;
            }
            set
            {
                OnMessageTypeChanging(value);
                ReportPropertyChanging("MessageType");
                _MessageType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageType");
                OnMessageTypeChanged();
            }
        }
        private global::System.String _MessageType;
        partial void OnMessageTypeChanging(global::System.String value);
        partial void OnMessageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageSwift
        {
            get
            {
                return _MessageSwift;
            }
            set
            {
                OnMessageSwiftChanging(value);
                ReportPropertyChanging("MessageSwift");
                _MessageSwift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageSwift");
                OnMessageSwiftChanged();
            }
        }
        private global::System.String _MessageSwift;
        partial void OnMessageSwiftChanging(global::System.String value);
        partial void OnMessageSwiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.TimeSpan _Time;
        partial void OnTimeChanging(global::System.TimeSpan value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Код_проверки_платежа
        {
            get
            {
                return _Код_проверки_платежа;
            }
            set
            {
                OnКод_проверки_платежаChanging(value);
                ReportPropertyChanging("Код_проверки_платежа");
                _Код_проверки_платежа = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Код_проверки_платежа");
                OnКод_проверки_платежаChanged();
            }
        }
        private Nullable<global::System.Int32> _Код_проверки_платежа;
        partial void OnКод_проверки_платежаChanging(Nullable<global::System.Int32> value);
        partial void OnКод_проверки_платежаChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Код_платежа
        {
            get
            {
                return _Код_платежа;
            }
            set
            {
                OnКод_платежаChanging(value);
                ReportPropertyChanging("Код_платежа");
                _Код_платежа = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Код_платежа");
                OnКод_платежаChanged();
            }
        }
        private Nullable<global::System.Int32> _Код_платежа;
        partial void OnКод_платежаChanging(Nullable<global::System.Int32> value);
        partial void OnКод_платежаChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] MessageObject
        {
            get
            {
                return StructuralObject.GetValidValue(_MessageObject);
            }
            set
            {
                OnMessageObjectChanging(value);
                ReportPropertyChanging("MessageObject");
                _MessageObject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageObject");
                OnMessageObjectChanged();
            }
        }
        private global::System.Byte[] _MessageObject;
        partial void OnMessageObjectChanging(global::System.Byte[] value);
        partial void OnMessageObjectChanged();

        #endregion
    }

    #endregion
    
}
